server:
  address: 0.0.0.0
  port: 8080

hibernate:
  hbm2ddl:
    auto: create
  search:
    default:
      directory_provider: filesystem
      indexBase: /var/lucene/indexes/base1


schema:
  qna
mynodename:
  node1

broker:
  address: localhost
  port: 5672
  vhost: /
  username: guest
  password: guest

#server:
#  address: 0.0.0.0
#  port: 8082
#
#hibernate:
#  hbm2ddl:
#    auto: create
#  search:
#    default:
#      directory_provider: filesystem
#      indexBase: /var/lucene/indexes/base2
#
#
#schema:
#  node2
#mynodename:
#  node2
#
#broker:
#  address: localhost
#  port: 5674
#  vhost: rabbit2
#  username: rabbit2
#  password: rabbit2